spring:
  profiles:
    active: local

---

spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
server:
  port: 8083

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mariadb://${MARIADB_URL}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate